```{r}
library(htmltab)
demolink = "https://en.wikipedia.org/wiki/Democracy_Index"
demopath = '//*[@id="mw-content-text"]/div/table[2]/tbody'
demo<- htmltab(doc = demolink, which =demopath)
```


```{r}
library(stringr)
library(magrittr)
```


```{r}
names(demo)=str_split(names(demo),">>",simplify = T)[,1]%>%gsub('\\s','',.)
```


```{r}
demo[,-c(1,8,9)]=lapply(demo[,-c(1,8,9)], trimws,whitespace = "[\\h\\v]") 
```


```{r}
demo=demo[,-c(1)]
```


```{r}
#esto no estaba en el resumen del profesor
demo$Changesfromlastyear=gsub(".*\\:","",demo$Changesfromlastyear)

#Para asi poder convertirlo en numérico y no toda esa columna se convierta en NA
```

```{r}
demo[,-c(1,8,9)]=lapply(demo[,-c(1,8,9)], as.numeric)
```

```{r}
str(demo)
```

```{r}
row.names(demo)=demo$Country

#para que es esto ¿? 
```

```{r}
demo=na.omit(demo)
```

```{r}
library(cluster)
```


```{r}
g.dist = daisy(demo[,c(3:7)], metric="gower")
```

```{r}
pam.resultado=pam(g.dist,4,cluster.only = F)

demo$clusterPT=pam.resultado$cluster
```


```{r}
library(plyr)
```

```{r}
aggregate(as.matrix(cbind(demo[,c(3:7)]))~ clusterPT, data=demo,FUN=plyr::each(MD = median, Media = mean))
```

```{r}
agg=aggregate(as.matrix(cbind(demo[,c(3:7)]))~ clusterPT, data=demo,FUN=plyr::each(MD = median, Media = mean))
```

```{r}
tablaResumen=t(as.data.frame(agg))
tablaResumen
```


```{r}
library(knitr)
library(kableExtra)
kable(tablaResumen, format = "html", digits = 2)%>%
  kable_styling()
```

```{r}
table(demo$clusterPT,demo$Regimetype,dnn = c('clusterPT','TipoEconomist'))
```

```{r}
demo[demo$clusterPT==1 & demo$Regimetype=="Flawed democracy",'Country']
```


```{r}
library(factoextra)
```

```{r}
fviz_cluster(object = list(data=g.dist, cluster = demo$clusterPT), geom = c("text"),ellipse.type = "convex")
```

